const Styles = {
    container: {
      // minHeight: "100vh",
      backgroundColor: "#f9fafb",
      padding: "24px",
      fontFamily: "Arial, sans-serif",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "24px",
    },
    cardGrid: {
      display: "grid",
      gap: "16px",
      gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
      marginBottom: "32px",
    },
    card: {
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
      padding: "16px",
    },
    cardText: {
      color: "#6b7280",
      fontSize: "14px",
    },
    cardValue: {
      fontSize: "24px",
      fontWeight: "600",
    },
    smallNote: {
      fontSize: "12px",
      color: "#9ca3af",
    },
    uploadSection: {
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      padding: "24px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
      marginBottom: "32px",
    },
    dashedBox: {
      border: "2px dashed #d1d5db",
      borderRadius: "12px",
      padding: "40px",
      textAlign: "center",
      color: "#6b7280",
    },
    floatingButton: {
      position: "fixed",
      bottom: "24px",
      right: "24px",
      background: "linear-gradient(to bottom right, #3b82f6, #8b5cf6)",
      color: "#ffffff",
      padding: "12px",
      borderRadius: "9999px",
      boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
      border: "none",
      fontSize: "18px",
      cursor: "pointer",
    },
    jobSection: {
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
      padding: "24px",
      marginBottom: "32px",
    },
    jobTitle: {
      fontSize: "20px",
      fontWeight: "bold",
      color: "#15803d",
    },
    jobDesc: {
      color: "#6b7280",
      fontSize: "14px",
      marginBottom: "12px",
    },
    textarea: {
      width: "100%",
      minHeight: "120px",
      borderRadius: "8px",
      padding: "12px",
      fontSize: "14px",
      border: "1px solid #e5e7eb",
      marginBottom: "16px",
      resize: "vertical",
      boxSizing: "border-box",
      outline:"none"
    },
    buttonGradient: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "linear-gradient(to right, #6366f1, #c084fc)",
      color: "white",
      padding: "12px",
      border: "none",
      borderRadius: "8px",
      width: "100%",
      fontSize: "14px",
      fontWeight: "600",
      cursor: "pointer",
    },
      topText: {
      fontSize: "20px",
      fontWeight: "bold",
      marginBottom: "30px",
      color: "#6366f1",
    },
    progressBar: {
      width: "100%",
      height: "30px",
      backgroundColor: "#f3f3f3",
      borderRadius: "25px",
      overflow: "hidden",
      border: "2px solid #555",
    },
    fill: {
      height: "100%",
      background: "linear-gradient(to right, #6366f1, #c084fc)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#fff",
      fontWeight: "bold",
      transition: "width 0.4s ease-in-out",
    },
    toggleContainer: {
      display: "flex",
      gap: "20px",
      marginBottom: 20,
    },
    toggleLabel: {
      fontSize: 16,
      color: "#2c3e50",
    },
    buttonGroup: {
      marginBottom: 20,
    },
    button: {
      padding: "10px 20px",
      marginRight: 10,
      borderRadius: 8,
      border: "none",
      cursor: "pointer",
      backgroundColor: "#3498db",
      color: "#fff",
      fontSize: 16,
    },
    transcriptBox: {
      marginTop: 20,
      marginBottom: 20,
      padding: 10,
      backgroundColor: "#ecf0f1",
      borderRadius: 8,
    },
  };


export default Styles;